# Stage 1 — Build
FROM golang:1.25 AS builder

WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bootstrap main.go

# Stage 2 — Lambda image
FROM public.ecr.aws/lambda/provided:al2
COPY --from=builder /build/bootstrap ${LAMBDA_RUNTIME_DIR}

CMD ["bootstrap"]